version: '3.1'

services:
  sls-node:
    image: postgres:15.1
    container_name: sls-node
    restart: always
    environment:
      POSTGRES_DB: sls-node
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5436:5436